### ISSUE TITLE
Blog Overview: Latest Article mehr hervorheben

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#11]
können wir die Section, in der der Latest Post steckt bitte in "Accent" hinterlegen?  

müsste das Bild des Latest nicht auch rechts größer sein und die breitere Section entsprechend ausnutzen? 
 
![image](https://github.com/user-attachments/assets/017377fb-273d-40cd-9c65-f3a18bcc1ac4)

**Comment by julrich** [comment]
Hintergrund-Farbe ist jetzt auf `accent` gesetzt, und es gab tatsächlich auch noch einen Bug in der Breitenberechnung für Sections. Das ist jetzt gefixed, und entsprechend wird auch das Bild größer (korrekt) ausgegeben!
https://www.ruhmesmeile.com/design-system-insights
