### ISSUE TITLE
Image Story: Aspect Ratio funktioniert nicht

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/ruhmesmeile#2]
Die `AspectRatio` property der Image Story hat scheinbar keine Auswirkung in Storyblok (im Storybook Funktioniert es):
![image](https://github.com/user-attachments/assets/4c6e22a0-b385-448a-96c8-88a77f51dc58)

**Comment by DanielLeyUX** [comment]
Irgendwas ist jetzt wieder mit den Bildern passiert. Auf der Seite hier, sind die jetzt alle süss klein :D 

https://ruhmesmeile.netlify.app/ux-strategie-beratung

![image](https://github.com/user-attachments/assets/66016ac8-bde4-4ebc-9768-9a2010ca07a9)

**Comment by julrich** [comment]
Those are all fixed now!
