### ISSUE TITLE
HTML Component / whitelist video site

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#24]
emedding shoud support e.g. youtube iframes

maybe we also support vimeo and google maps

**Comment by julrich** [comment]
Added all of those to the allowlist / whitelist (`frame-src 'self' https://youtube.com https://www.youtube.com https://player.vimeo.com *.google.com;`)

**Comment by julrich** [comment]
This should work as intended. If there's any issues left, feel free to just create a new issue!
