### ISSUE TITLE
Image / JS optimization for better performance

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#27]
Please check if images are optimized and dimensioned as expected

as one example/reminder
https://www.ruhmesmeile.com/design-system-insights/unterschiedliche-cms-loesungen-headless-vs-monolithische-systeme 

![image](https://github.com/user-attachments/assets/d207c281-663d-4b02-8815-b0f854447db1)

**Comment by julrich** [comment]
This is done, the only remaining thing for now is reducing Next.js JavaScript-complexity itself.
That effort is tracked here: https://github.com/kickstartDS/ruhmesmeile/pull/34
