### ISSUE TITLE
Blog Teaser: Images have no alt text prop/option

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#28]
could we use the image default ALT text from the DAM or should we provide an input in Storyblok for the Blog Teaser Image

**Comment by julrich** [comment]
This is now much improved: by default the `alt` field of the referenced asset will be pulled. If that doesn't it exist, it will fall back to the linked article headline. Additionally, you can override the assets `alt` by providing the newly added `alt` as part of the blog teaser itself.
