### ISSUE TITLE
Heros: Height props partly not working properly

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#31]
`Fullimage` or `Fullscreen` Height props are buggy.

**Comment by julrich** [comment]
Those now seem to work as intended, should be reviewed though.

I've added the following content to test:
https://www.ruhmesmeile.com/playground

Follow-up issue about `height` set to `small` having no real effect on mobile breakpoints:
https://github.com/kickstartDS/ds-agency-premium/issues/21

**Comment by julrich** [comment]
Closing this, as it seems to be working as intended to me.
