### ISSUE TITLE
Icons: Überschreibung von icons möglich machen

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/ruhmesmeile#4]
Wir brauchen einen Weg das Icons alte Icons zu ersetzen

**Comment by lmestel** [comment]
Das muss in der CLI gelöst werden

**Comment by lmestel** [comment]
Wobei... nicht zwingend

**Comment by fleven-kds** [comment]
Mit der aktuellen technischen Lösung werden **nur** die Icons geladen welche unter [token/dictionary/icons](https://github.com/kickstartDS/ruhmesmeile/tree/main/token/dictionary/icons) manuell hinzugefügt wurden.

**Comment by fleven-kds** [comment]
Des weiteren ist zu beachten dass man die icons vor dem verwenden in Flächen umwandeln muss und alle `fill` Werte entfernen muss.
@DanielLeyUX Alle Icons die wir verwenden sollten hier abgelegt werden: https://www.figma.com/design/S1cqDBmybBAq5dsQdM4GU2/ruhmesmeile.com?node-id=444-6953

**Comment by DanielLeyUX** [comment]
Hier mal eine Selection, von denen ich mir gut vorstellen könnte, die bei Featured und in Buttons zu verwenden

[feather_rm-selection.zip](https://github.com/user-attachments/files/16961513/feather_rm-selection.zip)

**Comment by fleven-kds** [comment]
Neues Icon Set ist eingesetzt, bei bedarf kann man weitere Icons hier einfügen:
https://github.com/kickstartDS/ruhmesmeile/tree/main/token/dictionary/icons
Die Svg's dürfen zur Verwendung keine Pfade und `fill` Attribute enthalten.
